/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

package com.mycompany.universidadg2.vistas;

/**
 *
 * @author ezequ
 */
public class vistaAlumno extends javax.swing.JInternalFrame {

    /** Creates new form vistaAlumno */
    public vistaAlumno() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPvistaAlumno = new javax.swing.JPanel();
        JLdni = new javax.swing.JLabel();
        JLnombre = new javax.swing.JLabel();
        JLfechadenacimiento = new javax.swing.JLabel();
        JTFid = new javax.swing.JTextField();
        JTFnombre = new javax.swing.JTextField();
        JLestado = new javax.swing.JLabel();
        JCestado = new javax.swing.JCheckBox();
        JDCfechadenacimiento = new com.toedter.calendar.JDateChooser();
        JBTNbuscar = new javax.swing.JButton();
        JLapellido = new javax.swing.JLabel();
        JTFapellido = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        JBTNguardar = new javax.swing.JButton();
        JBTNlimpiar = new javax.swing.JButton();
        JBTNborrar = new javax.swing.JButton();
        JBTNactualizar = new javax.swing.JButton();

        setClosable(true);

        JPvistaAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Formulario de alumnos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Microsoft Tai Le", 1, 18))); // NOI18N

        JLdni.setText("ID");

        JLnombre.setText("Nombre");

        JLfechadenacimiento.setText("Fecha de nacimiento");

        JLestado.setText("Estado");

        JBTNbuscar.setText("Buscar");

        JLapellido.setText("Apellido");

        JBTNguardar.setText("Guardar");

        JBTNlimpiar.setText("Limpiar");

        JBTNborrar.setText("Borrar");

        JBTNactualizar.setText("Actualizar");

        javax.swing.GroupLayout JPvistaAlumnoLayout = new javax.swing.GroupLayout(JPvistaAlumno);
        JPvistaAlumno.setLayout(JPvistaAlumnoLayout);
        JPvistaAlumnoLayout.setHorizontalGroup(
            JPvistaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPvistaAlumnoLayout.createSequentialGroup()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(JPvistaAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPvistaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPvistaAlumnoLayout.createSequentialGroup()
                        .addGroup(JPvistaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPvistaAlumnoLayout.createSequentialGroup()
                                .addComponent(JLfechadenacimiento)
                                .addGap(18, 18, 18)
                                .addComponent(JDCfechadenacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPvistaAlumnoLayout.createSequentialGroup()
                                .addComponent(JLapellido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFapellido))
                            .addGroup(JPvistaAlumnoLayout.createSequentialGroup()
                                .addGroup(JPvistaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLnombre)
                                    .addComponent(JLdni))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(JPvistaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFid)
                                    .addComponent(JTFnombre))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBTNbuscar)
                        .addGap(38, 38, 38))
                    .addGroup(JPvistaAlumnoLayout.createSequentialGroup()
                        .addComponent(JLestado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JCestado)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(JPvistaAlumnoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(JBTNguardar)
                .addGap(18, 18, 18)
                .addComponent(JBTNlimpiar)
                .addGap(18, 18, 18)
                .addComponent(JBTNborrar)
                .addGap(18, 18, 18)
                .addComponent(JBTNactualizar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JPvistaAlumnoLayout.setVerticalGroup(
            JPvistaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPvistaAlumnoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(JPvistaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLdni)
                    .addGroup(JPvistaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JTFid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JBTNbuscar)))
                .addGap(18, 18, 18)
                .addGroup(JPvistaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLnombre)
                    .addComponent(JTFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPvistaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPvistaAlumnoLayout.createSequentialGroup()
                        .addGroup(JPvistaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLapellido))
                        .addGap(18, 18, 18)
                        .addComponent(JLfechadenacimiento))
                    .addComponent(JDCfechadenacimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(JPvistaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPvistaAlumnoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JCestado))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPvistaAlumnoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(JLestado)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPvistaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTNguardar)
                    .addComponent(JBTNlimpiar)
                    .addComponent(JBTNborrar)
                    .addComponent(JBTNactualizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPvistaAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPvistaAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTNactualizar;
    private javax.swing.JButton JBTNborrar;
    private javax.swing.JButton JBTNbuscar;
    private javax.swing.JButton JBTNguardar;
    private javax.swing.JButton JBTNlimpiar;
    private javax.swing.JCheckBox JCestado;
    private com.toedter.calendar.JDateChooser JDCfechadenacimiento;
    private javax.swing.JLabel JLapellido;
    private javax.swing.JLabel JLdni;
    private javax.swing.JLabel JLestado;
    private javax.swing.JLabel JLfechadenacimiento;
    private javax.swing.JLabel JLnombre;
    private javax.swing.JPanel JPvistaAlumno;
    private javax.swing.JTextField JTFapellido;
    private javax.swing.JTextField JTFid;
    private javax.swing.JTextField JTFnombre;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

}
