/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.universidadg2.vistas;

/**
 *
 * @author martin
 */
public class vistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form vistaPrincipal
     */
    public vistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDvistaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMAlumno = new javax.swing.JMenu();
        JMIformulariodealumnos = new javax.swing.JMenuItem();
        JMMateria = new javax.swing.JMenu();
        JMIformulariodematerias = new javax.swing.JMenuItem();
        JMInscripciones = new javax.swing.JMenu();
        JMIformulariodeinscripciones = new javax.swing.JMenuItem();
        JMIcargadenotas = new javax.swing.JMenuItem();
        JMIlistadodealumnospormateria = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout JDvistaPrincipalLayout = new javax.swing.GroupLayout(JDvistaPrincipal);
        JDvistaPrincipal.setLayout(JDvistaPrincipalLayout);
        JDvistaPrincipalLayout.setHorizontalGroup(
            JDvistaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );
        JDvistaPrincipalLayout.setVerticalGroup(
            JDvistaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        JMAlumno.setText("Alumno");

        JMIformulariodealumnos.setText("Formulario de alumnos");
        JMIformulariodealumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIformulariodealumnosActionPerformed(evt);
            }
        });
        JMAlumno.add(JMIformulariodealumnos);

        jMenuBar1.add(JMAlumno);

        JMMateria.setText("Materia");

        JMIformulariodematerias.setText("Formulario de materias");
        JMIformulariodematerias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIformulariodemateriasActionPerformed(evt);
            }
        });
        JMMateria.add(JMIformulariodematerias);

        jMenuBar1.add(JMMateria);

        JMInscripciones.setText("Inscripciones");

        JMIformulariodeinscripciones.setText("Formulario de inscripciones");
        JMIformulariodeinscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIformulariodeinscripcionesActionPerformed(evt);
            }
        });
        JMInscripciones.add(JMIformulariodeinscripciones);

        JMIcargadenotas.setText("Carga de notas");
        JMIcargadenotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIcargadenotasActionPerformed(evt);
            }
        });
        JMInscripciones.add(JMIcargadenotas);

        JMIlistadodealumnospormateria.setText("Listado de alumnos por materia");
        JMIlistadodealumnospormateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIlistadodealumnospormateriaActionPerformed(evt);
            }
        });
        JMInscripciones.add(JMIlistadodealumnospormateria);

        jMenuBar1.add(JMInscripciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDvistaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDvistaPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMIformulariodealumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIformulariodealumnosActionPerformed
        JDvistaPrincipal.removeAll();
        JDvistaPrincipal.repaint();
        vistaAlumno formularioAlumno = new vistaAlumno();
        formularioAlumno.setVisible(true);
        JDvistaPrincipal.add(formularioAlumno);
        JDvistaPrincipal.moveToFront(formularioAlumno);
    }//GEN-LAST:event_JMIformulariodealumnosActionPerformed

    private void JMIformulariodemateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIformulariodemateriasActionPerformed
        JDvistaPrincipal.removeAll();
        JDvistaPrincipal.repaint();
        vistaMateria formularioMateria = new vistaMateria();
        formularioMateria.setVisible(true);
        JDvistaPrincipal.add(formularioMateria);
        JDvistaPrincipal.moveToFront(formularioMateria);
    }//GEN-LAST:event_JMIformulariodemateriasActionPerformed

    private void JMIformulariodeinscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIformulariodeinscripcionesActionPerformed
        JDvistaPrincipal.removeAll();
        JDvistaPrincipal.repaint();
        vistaInscripcion formularioInscripcion = new vistaInscripcion();
        formularioInscripcion.setVisible(true);
        JDvistaPrincipal.add(formularioInscripcion);
        JDvistaPrincipal.moveToFront(formularioInscripcion);
    }//GEN-LAST:event_JMIformulariodeinscripcionesActionPerformed

    private void JMIcargadenotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIcargadenotasActionPerformed
        JDvistaPrincipal.removeAll();
        JDvistaPrincipal.repaint();
        vistaNotas cargaDeNotas = new vistaNotas();
        cargaDeNotas.setVisible(true);
        JDvistaPrincipal.add(cargaDeNotas);
        JDvistaPrincipal.moveToFront(cargaDeNotas);
    }//GEN-LAST:event_JMIcargadenotasActionPerformed

    private void JMIlistadodealumnospormateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIlistadodealumnospormateriaActionPerformed
        JDvistaPrincipal.removeAll();
        JDvistaPrincipal.repaint();
        vistaListadoDeAlumnosxMateria listadoDeAlumnosPorMateria = new vistaListadoDeAlumnosxMateria();
        listadoDeAlumnosPorMateria.setVisible(true);
        JDvistaPrincipal.add(listadoDeAlumnosPorMateria);
        JDvistaPrincipal.moveToFront(listadoDeAlumnosPorMateria);
    }//GEN-LAST:event_JMIlistadodealumnospormateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JDvistaPrincipal;
    private javax.swing.JMenu JMAlumno;
    private javax.swing.JMenuItem JMIcargadenotas;
    private javax.swing.JMenuItem JMIformulariodealumnos;
    private javax.swing.JMenuItem JMIformulariodeinscripciones;
    private javax.swing.JMenuItem JMIformulariodematerias;
    private javax.swing.JMenuItem JMIlistadodealumnospormateria;
    private javax.swing.JMenu JMInscripciones;
    private javax.swing.JMenu JMMateria;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
